### ISSUE TITLE
It dose now work on newest version of flutter?

### ISSUE THREAD

**Issue by jarodtang** [Schwusch/widget_arrows#13]
Hi,

I tried the demo, it dose not work well.  Any fixes?

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

Br/Jarod

**Comment by Schwusch** [comment]
I tried on the latest Flutter and it seems to work.
I can repoen if the problem still persists.
