### ISSUE TITLE
Arrows are very much displaced in actual build!

### ISSUE THREAD

**Issue by sdoshi983** [Schwusch/widget_arrows#9]
As such, this package is **awesome**.👌 But I found some issues when the application is **finally built.**

![WhatsApp Image 2020-12-25 at 16 36 07](https://user-images.githubusercontent.com/60025677/103133969-a11ce000-46d3-11eb-8c60-4ea2c23c01a9.jpeg)

As you can see in the picture attached, the two pairs of arrows going from left to right and right to left are the next and previous pointers of the nodes of doubly linked list. Hence you can see it that where are the nodes and where are the arrows.

And the two arrows on top should be attached to the text "Head Pointer" and "Tail Pointer" respectively.

**NOTE**: The package is studied completely before using it. And the things are perfectly fine while developing (writing the code). This thing just happens when we build the application.

**OTHER THINGS**: The application is built several times from different machines and also tested on different mobile phones. The issue still persist!

Hence I request for getting help ASAP! Because this package is fantastic and can be used in many places.

**Comment by Schwusch** [comment]
Hi, I suspect it has to do with what @nezoat  points out in #5.
I don't have much time to work on this, though I am open to PRs!

**Comment by Schwusch** [comment]
I just released version 0.4.0 that might fix the problem.
I'll close the issue for now, but if the problem persists I can reopen.
